<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productsData = [
            [
                'id' => 'tote-field',
                'name' => 'Canvas Field Tote',
                'category' => 'Bags',
                'icon' => 'tote',
                'plate' => '#DCD3BC',
                'price' => 68,
                'desc' => 'A twelve-ounce cotton canvas tote built for market runs and daily carry. Bar-tacked handles and a reinforced base hold real weight without sagging.',
                'colors' => ['Olive', 'Sand', 'Charcoal'],
                'sizes' => null,
                'stock' => 14,
                'rating' => 4.6,
                'reviews' => 38,
            ],
            [
                'id' => 'tote-waxed',
                'name' => 'Waxed Canvas Tote',
                'category' => 'Bags',
                'icon' => 'tote',
                'plate' => '#C9A98A',
                'price' => 78,
                'compareAt' => 92,
                'desc' => 'Paraffin-waxed canvas sheds rain and wears in with a patina unique to its owner. Interior slip pocket keeps small essentials in place.',
                'colors' => ['Rust', 'Black'],
                'sizes' => null,
                'stock' => 9,
                'rating' => 4.8,
                'reviews' => 52,
            ],
            [
                'id' => 'jacket-chore',
                'name' => 'Chore Field Jacket',
                'category' => 'Outerwear',
                'icon' => 'jacket',
                'plate' => '#2F4B3C',
                'price' => 148,
                'desc' => 'A boxy, unlined chore coat in brushed cotton twill. Triple front pockets and a corduroy collar for cool mornings on site.',
                'colors' => ['Olive', 'Navy'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'stock' => 6,
                'rating' => 4.7,
                'reviews' => 64,
            ],
            [
                'id' => 'jacket-trucker',
                'name' => 'Waxed Trucker Jacket',
                'category' => 'Outerwear',
                'icon' => 'jacket',
                'plate' => '#4A4038',
                'price' => 168,
                'compareAt' => 195,
                'desc' => 'Waxed cotton shell with a wool blanket lining. Built for wind and drizzle, cut close enough to layer under a pack.',
                'colors' => ['Brown', 'Black'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'stock' => 4,
                'rating' => 4.9,
                'reviews' => 41,
            ],
            [
                'id' => 'boot-service',
                'name' => 'Service Leather Boot',
                'category' => 'Footwear',
                'icon' => 'boot',
                'plate' => '#6B4227',
                'price' => 210,
                'desc' => 'Full-grain leather uppers on a Goodyear-welted sole, built to be resoled for decades of wear. Breaks in fast, lasts long.',
                'colors' => ['Chestnut', 'Black'],
                'sizes' => ['7', '8', '9', '10', '11', '12'],
                'stock' => 11,
                'rating' => 4.8,
                'reviews' => 97,
            ],
            [
                'id' => 'boot-chukka',
                'name' => 'Trail Chukka Boot',
                'category' => 'Footwear',
                'icon' => 'boot',
                'plate' => '#B08654',
                'price' => 165,
                'desc' => 'A lighter chukka silhouette with a lugged rubber outsole for uneven ground. Suede upper, cotton laces.',
                'colors' => ['Tan'],
                'sizes' => ['7', '8', '9', '10', '11', '12'],
                'stock' => 0,
                'rating' => 4.5,
                'reviews' => 22,
            ],
            [
                'id' => 'mug-stoneware',
                'name' => 'Stoneware Mug',
                'category' => 'Home',
                'icon' => 'mug',
                'plate' => '#D8CBAE',
                'price' => 22,
                'desc' => 'Hand-thrown stoneware with a reactive glaze — every piece finishes slightly differently. Holds 12oz, dishwasher safe.',
                'colors' => ['Sand', 'Slate', 'Rust'],
                'sizes' => null,
                'stock' => 31,
                'rating' => 4.9,
                'reviews' => 18,
            ],
            [
                'id' => 'mug-enamel',
                'name' => 'Camp Enamel Mug',
                'category' => 'Home',
                'icon' => 'mug',
                'plate' => '#5F7A5A',
                'price' => 16,
                'desc' => 'Steel-core enamel mug for the campsite or the porch. Rolled rim, riveted handle, and a chip-resistant coating.',
                'colors' => ['Cream', 'Green'],
                'sizes' => null,
                'stock' => 24,
                'rating' => 4.4,
                'reviews' => 15,
            ],
            [
                'id' => 'journal-field',
                'name' => 'Field Notes Journal',
                'category' => 'Stationery',
                'icon' => 'notebook',
                'plate' => '#C7B89A',
                'price' => 18,
                'desc' => 'A pocket-sized dot-grid journal with a kraft cover and a sewn binding that lies flat at any page.',
                'colors' => ['Kraft', 'Black'],
                'sizes' => null,
                'stock' => 40,
                'rating' => 4.6,
                'reviews' => 29,
            ],
            [
                'id' => 'journal-leather',
                'name' => 'Leather Bound Journal',
                'category' => 'Stationery',
                'icon' => 'notebook',
                'plate' => '#6B4227',
                'price' => 42,
                'desc' => 'Refillable leather cover around a 240-page cotton paper insert. Ages into a journal worth keeping.',
                'colors' => ['Chestnut', 'Black'],
                'sizes' => null,
                'stock' => 17,
                'rating' => 4.7,
                'reviews' => 33,
            ],
            [
                'id' => 'belt-fullgrain',
                'name' => 'Full-Grain Belt',
                'category' => 'Accessories',
                'icon' => 'belt',
                'plate' => '#7A5232',
                'price' => 58,
                'desc' => 'A 1.5-inch full-grain leather belt with a solid brass buckle. Built on the same last as our boots for a matching patina.',
                'colors' => ['Brown', 'Black'],
                'sizes' => ['30', '32', '34', '36', '38', '40'],
                'stock' => 20,
                'rating' => 4.7,
                'reviews' => 26,
            ],
            [
                'id' => 'belt-webbing',
                'name' => 'Woven Web Belt',
                'category' => 'Accessories',
                'icon' => 'belt',
                'plate' => '#4A5D3A',
                'price' => 32,
                'desc' => 'Military-spec cotton webbing with a friction buckle — no holes needed, adjusts on the fly.',
                'colors' => ['Olive', 'Navy'],
                'sizes' => null,
                'stock' => 26,
                'rating' => 4.3,
                'reviews' => 12,
            ],
            [
                'id' => 'sweater-merino',
                'name' => 'Merino Crewneck Sweater',
                'category' => 'Knitwear',
                'icon' => 'sweater',
                'plate' => '#CBB89A',
                'price' => 98,
                'desc' => 'Fine-gauge merino wool, breathable enough for layering, warm enough on its own. Garment-washed for softness.',
                'colors' => ['Oatmeal', 'Forest'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'stock' => 13,
                'rating' => 4.8,
                'reviews' => 47,
            ],
            [
                'id' => 'sweater-shetland',
                'name' => 'Shetland Wool Sweater',
                'category' => 'Knitwear',
                'icon' => 'sweater',
                'plate' => '#8B4A34',
                'price' => 118,
                'compareAt' => 134,
                'desc' => 'Rustic Shetland wool with a fuller hand-feel and visible fiber texture. Ribbed cuffs and hem for a lasting shape.',
                'colors' => ['Charcoal', 'Rust'],
                'sizes' => ['S', 'M', 'L', 'XL'],
                'stock' => 8,
                'rating' => 4.6,
                'reviews' => 19,
            ],
            [
                'id' => 'wallet-bifold',
                'name' => 'Bifold Leather Wallet',
                'category' => 'Leather Goods',
                'icon' => 'wallet',
                'plate' => '#6B4227',
                'price' => 48,
                'desc' => 'Vegetable-tanned leather bifold with six card slots and a center bill pocket. Slim from day one, molds to your pocket.',
                'colors' => ['Brown', 'Black'],
                'sizes' => null,
                'stock' => 22,
                'rating' => 4.7,
                'reviews' => 35,
            ],
            [
                'id' => 'wallet-card',
                'name' => 'Card Holder Wallet',
                'category' => 'Leather Goods',
                'icon' => 'wallet',
                'plate' => '#B08654',
                'price' => 34,
                'desc' => 'A minimal front-pocket card case that holds four to six cards flat, with a center slot for folded bills.',
                'colors' => ['Tan', 'Black'],
                'sizes' => null,
                'stock' => 29,
                'rating' => 4.5,
                'reviews' => 21,
            ],
        ];

        foreach ($productsData as $item) {
            $category = Category::firstOrCreate(
                ['name' => $item['category']],
                [
                    'slug' => Str::slug($item['category']),
                    'status' => 'active',
                ]
            );

            $product = Product::create([
                'sku' => $item['id'],
                'name' => $item['name'],
                'slug' => Str::slug($item['name']) . '-' . $item['id'],
                'short_description' => Str::limit($item['desc'], 100),
                'description' => $item['desc'],
                'base_price' => $item['price'],
                'compare_price' => $item['compareAt'] ?? null,
                'status' => 'active',
                'is_active' => true,
                'is_featured' => ($item['rating'] >= 4.7),
                'icon' => $item['icon'],
                'plate' => $item['plate'],
                'colors' => $item['colors'],
                'sizes' => $item['sizes'],
                'stock' => $item['stock'],
                'rating' => $item['rating'],
                'reviews_count' => $item['reviews'],
            ]);

            $product->categories()->attach($category->id);
        }
    }
}
